apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "user-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}