apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-build
  labels:
    app: jenkins-agent
    purpose: microservice-build
spec:
  # Add this section:
  imagePullSecrets:
  - name: regcred # <--- This refers to the secret created in the jenkis machine
  # This secret should contain the Docker registry credentials
  # for pulling the jenkins/jnlp-agent image.

  containers:
  - name: jnlp
    image: jenkins/jnlp-agent:latest # No change needed here, it will now use the secret
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    env:
      - name: JENKINS_URL
        value: "http://178.254.23.139:8080/"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "200m"

  - name: build-tools
    image: tdksfot/jenkins-build-agent:latest
    command: ["cat"]
    tty: true
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m" # 1 CPU core
      requests:
        memory: "1Gi"
        cpu: "500m" # 0.5 CPU core
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: workspace-volume
      mountPath: /home/jenkins/agent/workspace

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  - name: workspace-volume
    emptyDir: {}